# docker-compose.yml

version: '3'

services:
  web:
    build: .
    command: gunicorn mypr.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

    

  

volumes:
  dbdata:
