# Generated by Django 5.0.7 on 2024-07-22 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
       
        
        migrations.AddField(
            model_name='item',
            name='brand_warranty',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='item',
            name='esn_number',
            field=models.CharField(default='001', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
        ),
        migrations.AddField(
            model_name='plan',
            name='assigned_retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plans', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('extended_warranty', 'Extended Warranty'), ('screen_protection', 'Screen Protection'), ('adld', 'ADLD'), ('complete_care', 'Complete Care'), ('service', 'Service')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailers', to='myapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('tv', 'TV'), ('ac', 'AC'), ('mobile', 'Mobile'), ('laptop', 'Laptop'), ('washing_machine', 'Washing Machine')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plan')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='managerassignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.managerassignment'),
        ),
        migrations.CreateModel(
            name='PartnerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.partner')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.partner')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('plan_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('plan_start_date', models.DateField(blank=True, null=True)),
                ('plan_end_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plan')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plan')),
                ('retailer', models.ForeignKey(limit_choices_to={'role': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='retailerassignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.retailerassignment'),
        ),
    ]
