# Generated by Django 5.0.7 on 2024-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_remove_plan_plan_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_end_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_start_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AlterField(
            model_name='item',
            name='esn_number',
            field=models.CharField(default='1001', max_length=255, unique=True),
        ),
    ]
